/**
 * cprmAgreementPack.js — the Commercial Property Rental Management Service
 * Agreement content pack (SSPC-CPRMS-01 v0.2). Same 25-clause + Schedule A/B/C/D
 * shape as the residential RPRM agreement, with the commercial wording and
 * service taxonomy from the source document. Consumed by rprmAgreement.service.js
 * which renders residential or commercial from a pack.
 */

// ── Schedule A: selectable commercial service groups (checkbox scope) ──────
const COMMERCIAL_SERVICE_GROUPS = {
  'Commercial Leasing': ['Rental Market Assessment', 'Commercial Leasing Consultation', 'Rental Pricing Guidance', 'Leasing Strategy', 'Lease Coordination', 'Lease Renewal Coordination'],
  'Marketing & Tenant Sourcing': ['Property Marketing', 'Professional Photography Coordination', 'Online Property Listings', 'Tenant Enquiries', 'Property Inspections', 'Corporate Tenant Sourcing', 'Business Tenant Sourcing', 'Preliminary Tenant Screening', 'Business Verification', 'Reference Checks'],
  'Property Management': ['Rent Collection Coordination', 'Tenant Communication', 'Routine Property Inspections', 'Lease Administration', 'Maintenance Coordination', 'Contractor Coordination', 'Occupancy Monitoring', 'Monthly Management Reporting'],
  'Additional Services': ['Utility Coordination', 'Signage Approval Coordination', 'Interior Fit-Out Coordination', 'Renovation Coordination', 'Legal Documentation Coordination', 'Property Improvement Coordination', 'Other'],
};

// ── Schedule D: commercial property management checklist groups ────────────
const COMMERCIAL_CHECKLIST_GROUPS = {
  'Property Setup': ['Property Ownership Verification', 'Trade Licence / Company Details', 'Property Address', 'Property Type & Floor Area', 'Current Occupancy Status', 'Utility Information'],
  'Marketing & Leasing': ['Target Rental Amount', 'Lease Requirements', 'Preferred Tenant Criteria', 'Listing Approved', 'Marketing Activated', 'Inspections Coordinated'],
  'Property Management': ['Rent Collection Authority', 'Maintenance Approval Limits', 'Contractor Preferences', 'Inspection Frequency', 'Owner Reporting Requirements'],
  'Completion / Closure': ['Lease Documentation Coordinated', 'Tenant Onboarding Completed', 'Handover Completed', 'Exit Inspection', 'Financial Settlement', 'Other Special Instructions'],
};

const ul = (items) => `<ul style="margin:4px 0 8px 18px;padding:0;list-style-type:disc;">${items.map((i) => `<li style="margin:2px 0;">${i}</li>`).join('')}</ul>`;

// ── The 25 clauses, faithful to Commercial Rental Management V0.2 ──────────
const COMMERCIAL_CLAUSES = [
  ['PURPOSE', `<p>This Agreement sets out the terms and conditions under which Seventh Sky will provide Commercial Property Rental Management Services to assist the Client in preparing, marketing, leasing and managing commercial property.</p><p>The Agreement establishes the rights and responsibilities of both Parties in relation to commercial leasing, tenant management, rent administration, inspections, maintenance coordination and ongoing property management.</p><p>The specific Services, pricing and management requirements applicable to each engagement shall be confirmed in the approved Quotation, Work Order or Commercial Property Management Schedule.</p>`],
  ['TERM', `<p>This Agreement becomes effective on the date it is signed by both Parties and continues until:</p>${ul(['the agreed Services have been completed;', 'all outstanding payments have been made;', 'all obligations under this Agreement have been fulfilled; or', 'this Agreement is terminated in accordance with its terms.'])}<p>Where ongoing commercial property management services are engaged, this Agreement continues until terminated by either Party in accordance with this Agreement.</p>`],
  ['SERVICES', `<p>Depending on the selected Service Package, Seventh Sky may provide one or more of the Services listed in <b>Schedule A</b> (Commercial Leasing; Marketing &amp; Tenant Sourcing; Property Management; and Additional Services). Only the Services selected in Schedule A or the approved Work Order form part of this Agreement. Additional Services may be included by written agreement.</p>`],
  ['COMMERCIAL PROPERTY DETAILS', `<p>The details of each commercial property shall be recorded in <b>Schedule B</b> or the approved Work Order, and may include:</p>${ul(['Property Address; Property Type; Floor Area; Building Size;', 'Current Occupancy Status; Intended Use; Target Rental Amount;', 'Lease Requirements; Management Commencement Date;', 'Selected Services; and Special Instructions.'])}<p>Where any inconsistency exists between this Agreement and the approved Work Order or Property Management Schedule, the approved Work Order or Property Management Schedule shall prevail for that engagement.</p>`],
  ['RESPONSIBILITIES OF SEVENTH SKY', `<p>Seventh Sky will:</p>${ul(['provide the agreed Services with reasonable care, skill and professional diligence;', 'coordinate property marketing and commercial leasing activities;', 'coordinate tenant enquiries and preliminary tenant screening;', 'coordinate lease documentation and lease renewal where included within the agreed Services;', 'coordinate rent collection where authorised;', 'coordinate routine inspections and maintenance requests;', 'coordinate approved contractors and third-party service providers where authorised;', 'provide periodic management reports where included within the selected Service Package;', 'maintain appropriate records relating to the Services; and', 'keep the Client reasonably informed throughout the management period.'])}<p>Unless otherwise agreed in writing, Seventh Sky acts solely as a Commercial Property Rental Management Service Provider and Coordinator and does not act as the property owner, landlord, tenant, legal adviser, valuer, surveyor, accountant, insurer or government authority.</p>`],
  ['OWNER RESPONSIBILITIES', `<p>The Client agrees to:</p>${ul(['provide accurate ownership and property information;', 'confirm that they have lawful authority to lease and manage the property;', 'ensure the property complies with all applicable legal and regulatory requirements;', 'provide access for inspections, photography and leasing activities;', 'provide approvals reasonably required for maintenance and operational decisions;', 'maintain appropriate insurance where applicable;', 'pay all agreed Service Fees and approved third-party costs;', 'promptly notify Seventh Sky of any material changes affecting the property; and', 'cooperate throughout the management period.'])}<p>The Client remains responsible for ownership and legal compliance, taxation and insurance obligations, financing arrangements, structural repairs, statutory approvals, government charges, major maintenance and capital improvement costs unless otherwise agreed, and the accuracy of all information provided to Seventh Sky.</p>`],
  ['QUOTATIONS & WORK ORDERS', `<p>Before commencing the Services, Seventh Sky may issue a Quotation or Work Order specifying the agreed Services, selected Service Package, management commencement date, Service Fees, approved third-party costs, payment schedule, expected project timeframe and any special conditions. Additional Services requested after commencement may require a revised Quotation, Work Order or approved variation before work proceeds.</p>`],
  ['SERVICE FEES & PAYMENT', `<p>The Service Fees payable under this Agreement shall be specified in the approved Quotation, Work Order or Commercial Property Management Schedule. Depending on the selected Service Package, the Service Fees may include Initial Consultation, Rental Market Assessment, Commercial Leasing Services, Property Marketing, Tenant Sourcing and Preliminary Screening, Lease Coordination, Rent Collection Coordination, Property Management Services, Routine Property Inspections, Maintenance Coordination, Lease Renewal Coordination, Approved Third-Party Costs and Additional Services requested by the Client.</p><p>The Client agrees to pay all agreed Service Fees in accordance with the approved payment schedule. Government charges, taxes, insurance premiums, legal expenses, utility charges, maintenance costs, contractor fees and other approved operational expenses remain the responsibility of the Client unless otherwise agreed in writing.</p>`],
  ['PAYMENT TERMS', `<p>Unless otherwise agreed in writing, Professional Service Fees shall be payable in accordance with the approved Quotation, Work Order or Commercial Property Management Schedule. Where ongoing property management services are provided, the Parties may agree to one of the following pricing models:</p>${ul(['Fixed Monthly Management Fee;', 'Percentage of Monthly Rent Collected;', 'Hybrid Fee (Fixed Fee plus Percentage of Rent); or', 'Another pricing structure agreed in writing.'])}<p>Where authorised by the Client, Seventh Sky may deduct agreed management fees and approved expenses from rent collected before remitting the balance to the Client. Invoices are payable within the period stated on the invoice. Late payments may result in suspension of the Services until outstanding amounts have been paid.</p>`],
  ['COMMERCIAL PROPERTY RENTAL MANAGEMENT SERVICES', `<p>Seventh Sky will use reasonable efforts to market, lease and manage the Property in accordance with the agreed scope of Services, which depending on the selected Service Package may include rental market assessment, commercial property marketing, tenant enquiries, preliminary tenant screening, lease coordination, rent collection coordination, tenant communication, routine property inspections, maintenance coordination, contractor coordination, lease renewal coordination, occupancy monitoring, management reporting and other agreed commercial property management services.</p><p>The Client acknowledges that leasing outcomes depend on market conditions and tenant demand; rental values may change over time; prospective tenants may decide not to proceed with a lease; the Client retains the final decision regarding tenant approval unless otherwise authorised in writing; and Seventh Sky does not guarantee uninterrupted occupancy, rental income or lease renewal.</p>`],
  ['PROJECT TIMELINES', `<p>Estimated commencement and completion dates will be provided in the approved Quotation, Work Order or Commercial Property Management Schedule where applicable. Project timeframes may vary depending on market demand, tenant availability, Client approvals, lease negotiations, maintenance or fit-out requirements, contractor availability, government approvals, public holidays and other circumstances beyond Seventh Sky's reasonable control. Where delays occur, Seventh Sky will keep the Client reasonably informed and provide revised estimated timeframes where reasonably practicable.</p>`],
  ['VARIATIONS & ADDITIONAL SERVICES', `<p>The Client may request changes to the agreed scope of Services at any time. Additional Services may include additional marketing campaigns, additional inspections, fit-out coordination, renovation coordination, contractor supervision, legal documentation coordination, signage approval coordination, property improvement projects or any other Services requested by the Client.</p><p>Where a variation affects the Service Fees, project scope or timeframe, Seventh Sky will provide a revised Quotation, Work Order or variation for approval before proceeding. Immediate action reasonably required to protect the Property, comply with legal obligations or ensure occupant safety may be undertaken without prior approval where obtaining approval is not reasonably practicable.</p>`],
  ['TENANT MANAGEMENT & THIRD-PARTY SERVICES', `<p>Where required, Seventh Sky may coordinate independent third-party professionals to support the delivery of the agreed Services, including lawyers, surveyors, valuers, accountants, contractors, insurers, utility providers, government authorities and other approved professional service providers.</p><p>The Client acknowledges that these providers operate independently and remain responsible for their own professional advice and services. Unless otherwise agreed in writing, Seventh Sky acts solely as the coordinator of these Services and is not responsible for the advice, reports, products or services provided by independent third parties.</p>`],
  ['SERVICE COMPLETION', `<p>The Services shall be deemed complete when Seventh Sky has substantially delivered the Services specified in the accepted Quotation, Work Order or Commercial Property Management Schedule. Depending on the agreed scope, completion may include the property prepared for leasing, marketing activities completed, tenant enquiries and preliminary screening completed, lease documentation coordinated, tenant onboarding completed where applicable, rent collection arrangements established where included, routine inspections completed, maintenance coordination completed and management reports issued.</p><p>Where ongoing property management services are engaged, the Services shall continue until the expiry or termination of the agreed management period unless renewed by mutual agreement.</p>`],
  ['CLIENT COMPLAINTS', `<p>If the Client is dissatisfied with any aspect of the Services, the Client should notify Seventh Sky as soon as reasonably practicable. Upon receiving a complaint, Seventh Sky will acknowledge receipt, investigate the matter, communicate with the Client throughout the review process, take reasonable steps to resolve the issue where appropriate, and advise the Client of the outcome.</p><p>Where a complaint relates to a tenant, contractor or other independent third-party service provider, Seventh Sky will assist in facilitating communication where reasonably practicable but is not responsible for that third party's acts, omissions or performance. Nothing in this Agreement limits any rights available under applicable law.</p>`],
  ['LIABILITY', `<p>Seventh Sky will perform the agreed Services with reasonable care, skill and professional diligence. The Client acknowledges that Seventh Sky acts solely as a Commercial Property Rental Management Service Provider and Coordinator and does not provide legal, financial, taxation, accounting, surveying, valuation, engineering, insurance or investment advice.</p><p>The Client remains responsible for ownership and lawful leasing of the Property, compliance with all applicable laws and lease obligations, insurance arrangements, taxation obligations, maintenance and repair approvals, compliance with building, planning and workplace regulations where applicable, and obtaining independent professional advice where appropriate. Seventh Sky is not responsible for tenant decisions or conduct, tenant default or arrears, inaccurate information supplied by the Client, tenants or third parties, the acts or omissions of independent contractors or service providers, or professional advice provided by independent third-party professionals.</p>`],
  ['LIMITATION OF LIABILITY', `<p>To the maximum extent permitted by law, Seventh Sky shall not be liable for:</p>${ul(['failure to secure or retain tenants;', 'rental vacancies or changes in market conditions;', 'tenant default, rental arrears or breaches of tenancy agreements;', 'damage caused by tenants, contractors or third parties;', 'delays caused by contractors, utility providers or government authorities;', 'delays in fit-out, maintenance or renovation works;', 'business interruption, loss of rental income, loss of profit, loss of goodwill or other indirect or consequential loss; or', "events beyond Seventh Sky's reasonable control."])}<p>Where liability cannot legally be excluded, Seventh Sky's total liability shall not exceed the Professional Service Fees paid by the Client for the Services giving rise to the claim. Nothing in this clause excludes liability that cannot legally be excluded under applicable law.</p>`],
  ['CONFIDENTIALITY & PRIVACY', `<p>Both Parties agree to keep confidential all non-public information obtained through this Agreement. Seventh Sky may collect, use and disclose information only for the purpose of providing the agreed Services, marketing and managing the Property, communicating with the Client, prospective tenants and authorised third parties, coordinating contractors and approved service providers, preparing quotations, reports, invoices and management records, complying with legal obligations, and managing its business operations.</p><p>Neither Party shall disclose confidential information to any third party without prior consent unless required by law. These obligations continue after completion or termination of this Agreement.</p>`],
  ['FORCE MAJEURE', `<p>Neither Party shall be liable for delays or failure to perform its obligations where caused by events beyond its reasonable control, including natural disasters, floods, fire, pandemics, government restrictions, industrial action, utility failures, civil unrest or other unforeseen events. The affected Party shall notify the other Party as soon as reasonably practicable and resume performance once the event has ended.</p>`],
  ['OWNER ACKNOWLEDGEMENTS', `<p>The Client acknowledges that:</p>${ul(['they have read and understood this Agreement;', 'all information provided to Seventh Sky is true, accurate and complete to the best of their knowledge;', 'Seventh Sky provides Commercial Property Rental Management Services only and does not own, lease or control the Property;', 'successful leasing depends on market conditions, tenant demand and the suitability of the Property;', 'the final decision to approve or reject a tenant remains with the Client unless otherwise authorised in writing;', 'rental values and occupancy levels may change over time;', 'independent legal, taxation, accounting, financial, engineering and other professional advice should be obtained where appropriate;', 'independent third-party professionals remain responsible for their own advice and services;', 'all agreed Professional Service Fees, approved expenses and third-party costs remain payable in accordance with this Agreement; and', 'they have had the opportunity to obtain independent legal advice before entering into this Agreement.'])}`],
  ['SUSPENSION & TERMINATION', `<p><b>21.1 Suspension.</b> Seventh Sky may suspend all or part of the Services where the Client fails to pay any outstanding amount, provides false, misleading or incomplete information, fails to provide information, approvals or instructions reasonably required, requests Seventh Sky to undertake any unlawful activity, or commits a material breach of this Agreement. Where reasonably practicable, Seventh Sky will notify the Client before suspending the Services.</p><p><b>21.2 Termination.</b> Either Party may terminate this Agreement by providing written notice to the other Party. Seventh Sky may terminate immediately where the Client commits a material breach, repeatedly fails to pay agreed Service Fees, engages in fraudulent or unlawful conduct, intentionally circumvents Seventh Sky, or otherwise acts in a manner that makes continuation of the Services unreasonable. Upon termination, Professional Service Fees for Services already completed, approved third-party costs and management fees accrued before termination remain payable; obligations intended to survive termination continue; and termination does not affect rights or obligations accrued before the termination date.</p>`],
  ['NON-CIRCUMVENTION', `<p>The Client acknowledges that Seventh Sky invests considerable time, expertise and commercial resources in marketing commercial properties, sourcing prospective tenants and coordinating leasing and property management services. Accordingly, where Seventh Sky introduces a prospective tenant, the Client agrees not to intentionally bypass Seventh Sky to avoid payment of the agreed Professional Service Fees or Management Fees.</p><p>This obligation applies during the term of this Agreement and for twelve (12) months following the introduction of the relevant prospective tenant. This clause does not prevent the Client from entering into a lease with a tenant who was not introduced by Seventh Sky.</p>`],
  ['GENERAL PROVISIONS', `<p>Unless otherwise agreed in writing, this Agreement together with the accepted Quotation, Work Order and Schedules constitutes the entire agreement between the Parties; any amendment must be made in writing and accepted by both Parties; failure by either Party to enforce any provision shall not constitute a waiver of that provision; if any provision is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect; and notices under this Agreement may be delivered by hand, registered post, courier or email.</p>`],
  ['GOVERNING LAW', `<p>This Agreement shall be governed by the laws of the People's Republic of Bangladesh. The Parties agree to use reasonable efforts to resolve any dispute through good faith discussions before commencing legal proceedings. Where a dispute cannot be resolved through negotiation, either Party may refer the matter to the competent courts of Bangladesh.</p>`],
  ['EXECUTION', `<p>By signing this Agreement, the Parties confirm that they have read and understood this Agreement, have had the opportunity to obtain independent legal advice, agree to be bound by its terms, and enter into it voluntarily. This Agreement may be executed in counterparts and by electronic signature, each of which shall be deemed an original.</p>`],
];

const COMMERCIAL_PACK = {
  doc_no: 'SSPC-CPRMS-01',
  title: 'Commercial Property Rental Management Service Agreement',
  catalog_vertical: 'commercial_pm',
  related_type: 'commercial_property_management_agreement',
  cover_kicker: 'Commercial Asset & Rental Management',
  hero_eyebrow: 'Commercial Leasing & Asset Management',
  hero_title_html: 'Commercial Property<br/>Rental Management<br/>Service Agreement',
  cover_intro: 'A governance framework establishing commercial terms, marketing &amp; leasing standards, rent administration, routine inspections and full asset care covenants between Seventh Sky Property Care and the Commercial Property Owner / Landlord.',
  owner_label: 'Property Owner / Landlord (Client)',
  schedule_b_title: 'SCHEDULE B — Commercial Property Management Summary',
  schedule_d_title: 'SCHEDULE D — Commercial Property Management Checklist',
  clauses: COMMERCIAL_CLAUSES,
  service_groups: COMMERCIAL_SERVICE_GROUPS,
  checklist_groups: COMMERCIAL_CHECKLIST_GROUPS,
};

module.exports = { COMMERCIAL_PACK, COMMERCIAL_CLAUSES, COMMERCIAL_SERVICE_GROUPS, COMMERCIAL_CHECKLIST_GROUPS };
