/**
 * cptmAgreementPack.js — the Commercial Property Tenancy Management Service
 * Agreement content pack (SSPC-CPTMS-01 v0.2). Tenant-side service (Seventh Sky
 * assists the commercial Tenant to locate, secure and manage a tenancy). Same
 * 25-clause + Schedule A/B/C/D shape as the residential RPTM agreement, with the
 * commercial tenant wording and service taxonomy from the source document.
 */

// ── Schedule A: selectable commercial tenancy service groups ──────────────
const COMMERCIAL_TENANCY_SERVICE_GROUPS = {
  'Commercial Tenancy Consultation': ['Commercial Leasing Consultation', 'Property Search Assistance', 'Rental Market Guidance', 'Lease Planning', 'Business Location Advice'],
  'Property Search & Leasing': ['Commercial Property Search', 'Property Inspection Coordination', 'Property Evaluation Assistance', 'Landlord Communication', 'Lease Negotiation Coordination', 'Lease Documentation Coordination', 'Lease Signing Coordination', 'Handover Coordination'],
  'Tenancy Management': ['Utility Connection Coordination', 'Move-in Coordination', 'Lease Administration', 'Maintenance Request Coordination', 'Lease Renewal Coordination', 'Ongoing Tenancy Support'],
  'Additional Services': ['Interior Fit-Out Coordination', 'Signage Approval Coordination', 'Business Setup Coordination', 'Renovation Coordination', 'Legal Documentation Coordination', 'Other'],
};

// ── Schedule D: commercial tenancy management checklist groups ────────────
const COMMERCIAL_TENANCY_CHECKLIST_GROUPS = {
  'Tenant Information': ['Tenant / Company Details', 'Trade Licence / Business Registration', 'Intended Business Use', 'Required Floor Area', 'Rental Budget'],
  'Property Search & Leasing': ['Property Shortlist Prepared', 'Inspections Coordinated', 'Lease Negotiation Coordinated', 'Lease Documentation Coordinated', 'Lease Signed'],
  'Tenancy Commencement': ['Security Deposit / Advance Rent', 'Utility Connections Arranged', 'Move-in Coordinated', 'Handover Completed', 'Fit-Out / Signage Approvals'],
  'Completion / Closure': ['Lease Administration Setup', 'Renewal Reminders Set', 'Supporting Documents Filed', 'Other Special Instructions'],
};

const ul = (items) => `<ul style="margin:4px 0 8px 18px;padding:0;list-style-type:disc;">${items.map((i) => `<li style="margin:2px 0;">${i}</li>`).join('')}</ul>`;

const COMMERCIAL_TENANCY_CLAUSES = [
  ['PURPOSE', `<p>This Agreement sets out the terms and conditions under which Seventh Sky will provide Commercial Property Tenancy Management Services to assist the Tenant in locating, securing, commencing and managing a commercial tenancy.</p><p>The Agreement establishes the rights and responsibilities of the Parties in relation to property search, lease coordination, tenancy administration, inspections, landlord communication and other agreed tenancy support services.</p><p>The specific Services, pricing and tenancy requirements applicable to each engagement shall be confirmed in the approved Quotation, Work Order or Schedule B.</p>`],
  ['TERM', `<p>This Agreement becomes effective on the date it is signed by both Parties and continues until:</p>${ul(['the agreed Services have been completed;', 'the tenancy has commenced or concluded, where applicable;', 'all outstanding obligations have been fulfilled; or', 'this Agreement is terminated in accordance with its terms.'])}<p>Where ongoing tenancy management services are engaged, this Agreement continues until terminated by either Party in accordance with this Agreement.</p>`],
  ['SERVICES', `<p>Depending on the selected Service Package, Seventh Sky may provide one or more of the Services listed in <b>Schedule A</b> (Commercial Tenancy Consultation; Property Search &amp; Leasing; Tenancy Management; and Additional Services). Only the Services selected in Schedule A or the approved Work Order form part of this Agreement. Additional Services may be included by written agreement.</p>`],
  ['COMMERCIAL TENANCY DETAILS', `<p>The tenancy details shall be recorded in <b>Schedule B</b> or the approved Work Order, and may include:</p>${ul(['Property Address; Property Type; Intended Business Use;', 'Tenant Details; Required Floor Area;', 'Lease Commencement Date; Lease Duration; Rental Budget;', 'Selected Services; and Special Requirements.'])}<p>Where any inconsistency exists between this Agreement and the approved Work Order or Schedule B, the approved Work Order or Schedule B shall prevail for that engagement.</p>`],
  ['TENANT RESPONSIBILITIES', `<p>The Tenant agrees to:</p>${ul(['provide accurate personal, business and financial information;', 'provide documents reasonably required for the tenancy process;', 'promptly review and approve quotations, lease documentation and related correspondence;', 'comply with all applicable laws and lease obligations;', 'pay all agreed Service Fees and approved third-party costs;', 'cooperate with Seventh Sky, the Property Owner and other relevant parties;', 'promptly notify Seventh Sky of any material changes affecting the tenancy; and', 'obtain all licences, permits and approvals required for their business activities.'])}<p>The Tenant remains responsible for compliance with the executed lease agreement, taxation and business obligations, business insurance where applicable, business operations conducted from the premises, and obligations owed directly to the Property Owner.</p>`],
  ['RESPONSIBILITIES OF SEVENTH SKY', `<p>Seventh Sky will:</p>${ul(['provide the agreed Services with reasonable care, skill and professional diligence;', 'assist the Tenant in identifying suitable commercial properties;', 'coordinate inspections and communication with Property Owners or their representatives;', 'coordinate lease negotiations and lease documentation where included within the agreed Services;', 'coordinate tenancy commencement and handover arrangements;', 'coordinate utility connections and approved tenancy support services;', 'maintain appropriate records relating to the Services; and', 'keep the Tenant reasonably informed throughout the engagement.'])}<p>Unless otherwise agreed in writing, Seventh Sky acts solely as a Commercial Property Tenancy Management Service Provider and Coordinator and does not become the Property Owner, landlord, lessor, legal adviser, financial adviser, valuer or real estate agent for either Party.</p>`],
  ['QUOTATIONS & WORK ORDERS', `<p>Before commencing the Services, Seventh Sky may issue a Quotation or Work Order specifying the agreed Services, selected Service Package, Service Fees, approved third-party costs, payment schedule, expected service timeframe and any special conditions. Additional Services requested after commencement may require a revised Quotation, Work Order or approved variation before work proceeds.</p>`],
  ['SERVICE FEES & PAYMENT', `<p>The Service Fees payable under this Agreement shall be specified in the approved Quotation, Work Order or Schedule B. Depending on the selected Service Package, the Service Fees may include Commercial Tenancy Consultation, Commercial Property Search, Rental Market Guidance, Property Inspection Coordination, Lease Negotiation Coordination, Lease Documentation Coordination, Tenancy Commencement Coordination, Utility Connection Coordination, Ongoing Tenancy Support, Approved Third-Party Costs and Additional Services requested by the Tenant.</p><p>The Tenant agrees to pay all agreed Service Fees in accordance with the approved payment schedule. Government charges, stamp duty, registration fees, security deposits, advance rent, legal expenses, utility connection fees, fit-out costs and other tenancy-related expenses remain the responsibility of the Tenant unless otherwise agreed in writing.</p>`],
  ['PAYMENT TERMS', `<p>Unless otherwise agreed in writing, Professional Service Fees shall be payable in accordance with the approved Quotation, Work Order or Schedule B. Where ongoing tenancy support services are provided, the Parties may agree to:</p>${ul(['Fixed Monthly Fee;', 'Service Fee Per Request;', 'Annual Service Package; or', 'Another pricing structure agreed in writing.'])}<p>Invoices are payable within the period stated on the invoice. Late payment may result in suspension of non-essential Services until outstanding amounts have been paid.</p>`],
  ['COMMERCIAL TENANCY MANAGEMENT SERVICES', `<p>Seventh Sky will use reasonable efforts to assist the Tenant in locating, securing and managing a suitable commercial tenancy in accordance with the agreed scope of Services, which may include commercial property search, property inspection coordination, landlord communication, lease negotiation coordination, lease documentation coordination, tenancy commencement coordination, utility connection coordination, maintenance request coordination, lease administration, lease renewal coordination and other agreed tenancy support services.</p><p>The Tenant acknowledges that property availability depends on market conditions; rental rates and lease terms may change before a lease is executed; the Property Owner retains the right to accept or reject tenancy applications; leasing outcomes depend on negotiations between the Property Owner and the Tenant; and Seventh Sky does not guarantee that a particular property will remain available or that a lease application will be accepted.</p>`],
  ['SERVICE TIMELINES', `<p>Estimated timeframes for the delivery of the Services will be provided in the approved Quotation, Work Order or Schedule B where applicable. Service delivery may be affected by property availability, landlord response times, lease negotiations, document preparation, government approvals, banking or financial approvals, utility providers, public holidays and other circumstances beyond Seventh Sky's reasonable control. Where delays occur, Seventh Sky will keep the Tenant reasonably informed and provide revised estimated timeframes where reasonably practicable.</p>`],
  ['VARIATIONS & ADDITIONAL SERVICES', `<p>The Tenant may request changes to the agreed scope of Services at any time. Additional Services may include additional property inspections, additional lease negotiations, property searches outside the agreed area, fit-out coordination, signage approval coordination, business setup coordination, legal documentation coordination or any other Services requested by the Tenant.</p><p>Where a variation affects the Service Fees, scope of Services or delivery timeframe, Seventh Sky will provide a revised Quotation, Work Order or variation for approval before proceeding. Immediate action reasonably required to protect the Tenant's interests or comply with legal obligations may be undertaken without prior approval where obtaining approval is not reasonably practicable.</p>`],
  ['THIRD-PARTY SERVICES', `<p>Where required, Seventh Sky may coordinate independent third-party professionals to support the delivery of the agreed Services, including Property Owners or their authorised representatives, lawyers, accountants, banks and financial institutions, contractors, utility providers, government authorities and other professional service providers.</p><p>The Tenant acknowledges that these providers operate independently and remain responsible for their own advice, products and services. Unless otherwise agreed in writing, Seventh Sky acts solely as the coordinator of these Services and is not responsible for the advice, decisions, products or services provided by independent third parties.</p>`],
  ['SERVICE COMPLETION', `<p>The Services shall be deemed complete when Seventh Sky has substantially delivered the Services specified in the accepted Quotation, Work Order or Schedule B. Depending on the agreed scope, completion may include commercial property search completed, property inspections coordinated, lease negotiations completed, lease documentation coordinated, tenancy commencement coordinated, utility connection arrangements completed, tenancy handover completed and lease renewal coordination completed.</p><p>Where ongoing tenancy management services are engaged, the Services shall continue until the expiry or termination of the agreed service period unless renewed by mutual agreement.</p>`],
  ['CLIENT COMPLAINTS', `<p>If the Tenant is dissatisfied with any aspect of the Services, the Tenant should notify Seventh Sky as soon as reasonably practicable. Upon receiving a complaint, Seventh Sky will acknowledge receipt, investigate the matter, communicate with the Tenant throughout the review process, take reasonable steps to resolve the issue where appropriate, and advise the Tenant of the outcome.</p><p>Where a complaint relates to a Property Owner or another independent third-party service provider, Seventh Sky will assist in facilitating communication where reasonably practicable but is not responsible for that third party's acts, omissions or performance. Nothing in this Agreement limits any rights available under applicable law.</p>`],
  ['LIABILITY', `<p>Seventh Sky will perform the agreed Services with reasonable care, skill and professional diligence. The Tenant acknowledges that Seventh Sky acts solely as a Commercial Property Tenancy Management Service Provider and Coordinator and does not provide legal, financial, taxation, accounting, valuation, insurance or investment advice.</p><p>The Tenant remains responsible for decisions relating to the commercial lease, business operations conducted from the premises, compliance with lease obligations, obtaining required licences and approvals, taxation and insurance obligations, and obtaining independent professional advice where appropriate. Seventh Sky is not responsible for decisions made by Property Owners, acceptance or rejection of tenancy applications, changes to rental rates or lease conditions, inaccurate information supplied by the Tenant, Property Owner or third parties, the acts or omissions of independent contractors or service providers, or professional advice provided by independent third-party professionals.</p>`],
  ['LIMITATION OF LIABILITY', `<p>To the maximum extent permitted by law, Seventh Sky shall not be liable for:</p>${ul(['failure to secure a particular commercial property;', 'withdrawal of a property from the market;', 'changes to rental rates or lease conditions;', 'delays in lease negotiations or lease execution;', 'delays caused by Property Owners, banks, utility providers or government authorities;', 'business interruption, loss of profit, loss of business opportunity or other indirect or consequential loss;', 'decisions made by Property Owners or third parties; or', "events beyond Seventh Sky's reasonable control."])}<p>Where liability cannot legally be excluded, Seventh Sky's total liability shall not exceed the Professional Service Fees paid by the Tenant for the Services giving rise to the claim. Nothing in this clause excludes liability that cannot legally be excluded under applicable law.</p>`],
  ['CONFIDENTIALITY & PRIVACY', `<p>Both Parties agree to keep confidential all non-public information obtained through this Agreement. Seventh Sky may collect, use and disclose information only for the purpose of providing the agreed Services, identifying suitable commercial properties, communicating with Property Owners, landlords and authorised third parties, coordinating inspections, lease documentation and tenancy support services, preparing quotations, reports, invoices and management records, complying with legal obligations, and managing its business operations.</p><p>Neither Party shall disclose confidential information to any third party without prior consent unless required by law. These obligations continue after completion or termination of this Agreement.</p>`],
  ['FORCE MAJEURE', `<p>Neither Party shall be liable for delays or failure to perform its obligations where caused by events beyond its reasonable control, including natural disasters, floods, fire, pandemics, government restrictions, industrial action, utility failures, civil unrest or other unforeseen events. The affected Party shall notify the other Party as soon as reasonably practicable and resume performance once the event has ended.</p>`],
  ['TENANT ACKNOWLEDGEMENTS', `<p>The Tenant acknowledges that:</p>${ul(['they have read and understood this Agreement;', 'all information provided to Seventh Sky is true, accurate and complete to the best of their knowledge;', 'Seventh Sky provides Commercial Property Tenancy Management Services only and is not the Property Owner, landlord or lessor;', 'successful leasing depends on property availability, market conditions and negotiations with the Property Owner;', 'the Property Owner retains the final decision regarding tenancy applications and lease terms unless otherwise agreed;', 'rental rates and lease conditions may change before a lease is executed;', 'independent legal, taxation, accounting, financial and other professional advice should be obtained where appropriate;', 'independent third-party professionals remain responsible for their own advice and services;', 'all agreed Professional Service Fees, approved expenses and third-party costs remain payable in accordance with this Agreement; and', 'they have had the opportunity to obtain independent legal advice before entering into this Agreement.'])}`],
  ['SUSPENSION & TERMINATION', `<p><b>21.1 Suspension.</b> Seventh Sky may suspend all or part of the Services where the Tenant fails to pay any outstanding amount, provides false, misleading or incomplete information, fails to provide information or instructions reasonably required, requests Seventh Sky to undertake any unlawful activity, or commits a material breach of this Agreement. Where reasonably practicable, Seventh Sky will notify the Tenant before suspending the Services.</p><p><b>21.2 Termination.</b> Either Party may terminate this Agreement by providing written notice to the other Party. Seventh Sky may terminate immediately where the Tenant commits a material breach, repeatedly fails to pay agreed Service Fees, engages in fraudulent or unlawful conduct, intentionally circumvents Seventh Sky, or otherwise acts in a manner that makes continuation of the Services unreasonable. Upon termination, Professional Service Fees for Services already completed and approved third-party costs remain payable; obligations intended to survive termination continue; and termination does not affect rights or obligations accrued before the termination date.</p>`],
  ['NON-CIRCUMVENTION', `<p>The Tenant acknowledges that Seventh Sky invests considerable time, expertise and commercial resources in identifying suitable commercial properties, coordinating inspections, facilitating lease negotiations and managing tenancy support services. Accordingly, where Seventh Sky introduces a property, landlord or approved service provider, the Tenant agrees not to intentionally bypass Seventh Sky to avoid payment of the agreed Professional Service Fees.</p><p>This obligation applies during the term of this Agreement and for twelve (12) months following the relevant introduction. This clause does not restrict the Tenant from independently engaging with property owners or service providers who were not introduced by Seventh Sky.</p>`],
  ['GENERAL PROVISIONS', `<p>Unless otherwise agreed in writing, this Agreement together with the accepted Quotation, Work Order and Schedules constitutes the entire agreement between the Parties; any amendment must be made in writing and accepted by both Parties; failure by either Party to enforce any provision shall not constitute a waiver of that provision; if any provision is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect; and notices under this Agreement may be delivered by hand, registered post, courier or email.</p>`],
  ['GOVERNING LAW', `<p>This Agreement shall be governed by the laws of the People's Republic of Bangladesh. The Parties agree to use reasonable efforts to resolve any dispute through good faith discussions before commencing legal proceedings. Where a dispute cannot be resolved through negotiation, either Party may refer the matter to the competent courts of Bangladesh.</p>`],
  ['EXECUTION', `<p>By signing this Agreement, the Parties confirm that they have read and understood this Agreement, have had the opportunity to obtain independent legal advice, agree to be bound by its terms, and enter into it voluntarily. This Agreement may be executed in counterparts and by electronic signature, each of which shall be deemed an original.</p>`],
];

const COMMERCIAL_TENANCY_PACK = {
  doc_no: 'SSPC-CPTMS-01',
  title: 'Commercial Property Tenancy Management Service Agreement',
  catalog_vertical: 'commercial_tenancy_mgmt',
  related_type: 'commercial_tenancy_management_agreement',
  cover_kicker: 'Commercial Tenancy & Leasing Support',
  hero_eyebrow: 'Commercial Tenant Representation',
  hero_title_html: 'Commercial Property<br/>Tenancy Management<br/>Service Agreement',
  cover_intro: 'A governance framework establishing commercial terms, property search &amp; leasing standards, tenancy commencement and ongoing tenancy support covenants between Seventh Sky Property Care and the Commercial Tenant.',
  owner_label: 'Commercial Tenant (Client)',
  provider_label: 'Service Provider · Tenant Representative',
  acting_line: 'Engagement: <strong>Commercial Tenant Representation & Leasing Support</strong>',
  footer_line: 'Seventh Sky Property Care · Commercial Tenancy Agreement SSPC-CPTMS-01 v0.2',
  schedule_b_title: 'SCHEDULE B — Commercial Tenancy Management Summary',
  schedule_d_title: 'SCHEDULE D — Commercial Tenancy Management Checklist',
  clauses: COMMERCIAL_TENANCY_CLAUSES,
  service_groups: COMMERCIAL_TENANCY_SERVICE_GROUPS,
  checklist_groups: COMMERCIAL_TENANCY_CHECKLIST_GROUPS,
};

module.exports = { COMMERCIAL_TENANCY_PACK, COMMERCIAL_TENANCY_CLAUSES, COMMERCIAL_TENANCY_SERVICE_GROUPS, COMMERCIAL_TENANCY_CHECKLIST_GROUPS };
