/**
 * rprmRuralAgreementPack.js — the Rural Property Rental Management Service
 * Agreement content pack (SSPC-RPRMS-RURAL-01 v0.2).
 *
 * Same 25-clause + Schedule A/B/C/D shape as the residential and commercial
 * packs, with the rural wording and service taxonomy from the source document.
 * Consumed by rprmAgreement.service.js, which renders whichever pack the
 * category resolves to.
 *
 * NOTE on the protection period: clause 22 of this agreement states TWELVE (12)
 * months, while the Rural Property Rental Management SOP §13 states 24 months.
 * The agreement is the document the client signs, so the clause below says 12.
 * The internal protection register is configured separately.
 */

// ── Schedule A: selectable rural service groups (checkbox scope) ───────────
const RURAL_SERVICE_GROUPS = {
  'Rental Preparation': ['Initial Consultation', 'Rural Property Assessment', 'Rental Pricing Guidance', 'Property Preparation Coordination', 'Marketing Strategy'],
  'Marketing & Tenant Sourcing': ['Property Marketing', 'Professional Photography Coordination', 'Online Property Listings', 'Tenant Sourcing', 'Tenant Screening', 'Lease Coordination'],
  'Property Management': ['Rent Collection Coordination', 'Tenant Communication', 'Routine Property Inspections', 'Property Condition Reporting', 'Maintenance Coordination', 'Contractor Coordination', 'Lease Renewal Coordination', 'Tenant Vacate Coordination'],
  'Rural Property Management': ['Agricultural Property Monitoring', 'Farm Supervision Coordination', 'Fishery / Pond Monitoring', 'Orchard Monitoring', 'Poultry / Dairy Farm Coordination', 'Caretaker Coordination', 'Security Coordination', 'Utility Coordination', 'Emergency Assistance Coordination', 'NRB Property Monitoring & Reporting'],
  'Additional Services': ['Legal Documentation Coordination', 'Property Valuation Coordination', 'Survey Coordination', 'Environmental Compliance Coordination', 'Other'],
};

// ── Schedule D: rural property rental management checklist groups ──────────
const RURAL_CHECKLIST_GROUPS = {
  'Property Preparation': ['Agreement Signed', 'Property Details Confirmed', 'Quotation / Work Order Approved', 'Property Assessment Completed', 'Rental Price Confirmed'],
  'Marketing & Leasing': ['Marketing Commenced', 'Tenant Enquiries Managed', 'Property Inspections Completed', 'Tenant Selected', 'Lease Coordinated'],
  'Property Management': ['Rent Collection Commenced', 'Routine Inspections Completed', 'Maintenance Requests Managed', 'Reports Issued'],
  'Rural Property Monitoring': ['Agricultural Monitoring Completed (If Applicable)', 'Caretaker Coordination Completed', 'Utility Coordination Completed', 'NRB Reports Issued (If Applicable)', 'File Closed'],
};

const ul = (items) => `<ul style="margin:4px 0 8px 18px;padding:0;list-style-type:disc;">${items.map((i) => `<li style="margin:2px 0;">${i}</li>`).join('')}</ul>`;

// ── The 25 clauses, faithful to Rural Property Rental Management V0.2 ──────
const RURAL_CLAUSES = [
  ['PURPOSE', `<p>This Agreement sets out the terms and conditions under which Seventh Sky will provide Rural Property Rental Management Services to assist the Client in preparing, marketing, leasing and managing a rural property.</p><p>The Agreement establishes the rights and responsibilities of both Parties in relation to rental preparation, tenant sourcing, leasing, rent administration, inspections, maintenance coordination, rural property management and other agreed management services.</p><p>The specific Services, pricing and management requirements applicable to each engagement shall be confirmed in the approved Quotation, Work Order or Rural Property Management Schedule.</p>`],
  ['TERM', `<p>This Agreement becomes effective on the date it is signed by both Parties and continues until:</p>${ul(['the agreed Services have been completed;', 'all outstanding payments have been made;', 'all obligations under this Agreement have been fulfilled; or', 'the Agreement is terminated in accordance with its terms.'])}<p>Where ongoing rural property management services are engaged, this Agreement continues until terminated by either Party in accordance with this Agreement.</p>`],
  ['SERVICES', `<p>Depending on the selected Service Package, Seventh Sky may provide one or more of the Services listed in <b>Schedule A</b> (Rental Preparation; Marketing &amp; Tenant Sourcing; Property Management; Rural Property Management; and Additional Services). Only the Services selected in Schedule A or the approved Work Order form part of this Agreement. Additional Services may be included by written agreement.</p>`],
  ['PROPERTY DETAILS', `<p>The details of each rural property shall be recorded in <b>Schedule B</b> or the approved Work Order, and may include:</p>${ul(['Property Address; District; Upazila; Union; Village;', 'Mouza; Khatian Number; Dag Number;', 'Property Type; Land Area; Ownership Details;', 'Expected Monthly Rent; Lease Requirements;', 'Selected Services; and Special Instructions.'])}<p>Where any inconsistency exists between this Agreement and the approved Work Order or Property Management Schedule, the approved Work Order or Property Management Schedule shall prevail for that engagement.</p>`],
  ['OWNER RESPONSIBILITIES', `<p>The Client agrees to:</p>${ul(['provide accurate ownership and property information;', 'confirm that they have lawful authority to lease and manage the property;', 'provide all documents reasonably required to perform the Services;', 'cooperate with inspections, marketing activities and tenant enquiries;', 'promptly notify Seventh Sky of any material changes affecting the property;', 'maintain appropriate insurance where applicable;', 'obtain independent legal, taxation, financial or technical advice where appropriate;', 'pay all agreed Service Fees and approved third-party costs; and', 'cooperate throughout the property management period.'])}<p>The Client remains responsible for ownership and legal compliance relating to the property, taxation and insurance obligations, maintenance and repair expenses, government charges and utility costs, agricultural or commercial operations conducted on the property, and the accuracy of all information provided to Seventh Sky.</p>`],
  ['RESPONSIBILITIES OF SEVENTH SKY', `<p>Seventh Sky will:</p>${ul(['provide the agreed Services with reasonable care, skill and professional diligence;', 'coordinate property preparation, marketing and tenant sourcing;', 'coordinate tenant enquiries, inspections and lease documentation;', 'coordinate rent collection where included within the agreed Services;', 'coordinate routine inspections and maintenance requests;', 'coordinate approved contractors and third-party service providers where authorised;', 'coordinate rural property monitoring services included within the agreed Service Package;', 'maintain appropriate records relating to the Services; and', 'keep the Client reasonably informed throughout the management period.'])}<p>Unless otherwise agreed in writing, Seventh Sky acts solely as a Rural Property Rental Management Service Provider and Coordinator and does not act as the property owner, landlord, tenant, legal adviser, surveyor, valuer, engineer, accountant, insurer or government authority.</p>`],
  ['QUOTATIONS & WORK ORDERS', `<p>Before commencing the Services, Seventh Sky may issue a Quotation or Work Order specifying the agreed Services, Service Package, management commencement date, Service Fees, approved third-party costs, payment schedule, expected project timeframe and any special conditions. Additional Services requested after commencement may require a revised Quotation, Work Order or approved variation before work proceeds.</p>`],
  ['SERVICE FEES & PAYMENT', `<p>The Service Fees payable under this Agreement shall be specified in the approved Quotation, Work Order or Rural Property Management Schedule. Depending on the selected Service Package, the Service Fees may include Initial Consultation, Rural Property Assessment, Rental Pricing Guidance, Property Preparation Coordination, Marketing and Advertising, Tenant Sourcing and Screening, Lease Coordination, Rent Collection Coordination, Property Management Services, Routine Property Inspections, Maintenance Coordination, Rural Property Monitoring Services, Approved Third-Party Costs and Additional Services requested by the Client.</p><p>The Client agrees to pay all agreed Service Fees in accordance with the approved payment schedule. Government charges, taxes, legal expenses, insurance premiums, utility charges, contractor costs, maintenance expenses and other property-related costs remain the responsibility of the Client unless otherwise agreed in writing.</p>`],
  ['PAYMENT TERMS', `<p>Unless otherwise agreed in writing, Professional Service Fees shall be payable in accordance with the approved Quotation, Work Order or Rural Property Management Schedule. Where ongoing property management services are provided, the Parties may agree to one of the following pricing models:</p>${ul(['Fixed Monthly Management Fee;', 'Percentage of Monthly Rent Collected;', 'Fixed Annual Management Fee; or', 'Another pricing structure agreed in writing.'])}<p>Where authorised by the Client, Seventh Sky may deduct agreed management fees and approved expenses from rent collected before remitting the balance to the Client. Invoices are payable within the period stated on the invoice. Late payments may result in suspension of the Services until outstanding amounts have been paid.</p>`],
  ['RURAL PROPERTY RENTAL MANAGEMENT SERVICES', `<p>Seventh Sky will use reasonable efforts to market, lease and manage the Property in accordance with the agreed scope of Services, which depending on the selected Service Package may include rental preparation, property marketing, tenant sourcing and preliminary screening, lease coordination, rent collection coordination, routine inspections, maintenance coordination, contractor coordination, caretaker coordination, rural property monitoring, utility coordination, emergency assistance coordination and other agreed property management services.</p><p>The Client acknowledges that successful leasing depends on market conditions and tenant demand; rental values may change over time; the Client retains the final decision regarding tenant approval unless otherwise authorised in writing; rent collection may be affected by tenant default or unforeseen circumstances; and Seventh Sky does not guarantee uninterrupted tenancy, rental income or agricultural outcomes.</p>`],
  ['PROJECT TIMELINES', `<p>Estimated commencement and completion dates will be provided in the approved Quotation, Work Order or Rural Property Management Schedule where applicable. Project timeframes may vary depending on market demand, tenant availability, property readiness, weather conditions, seasonal agricultural activities, maintenance requirements, contractor availability, government approvals, public holidays and other circumstances beyond Seventh Sky's reasonable control. Where delays occur, Seventh Sky will keep the Client reasonably informed and provide revised estimated timeframes where reasonably practicable.</p>`],
  ['VARIATIONS & ADDITIONAL SERVICES', `<p>The Client may request changes to the agreed scope of Services at any time. Additional Services may include additional marketing campaigns, additional inspections, emergency maintenance coordination, renovation coordination, engineering inspections, legal documentation coordination, environmental compliance coordination or any other Services requested by the Client.</p><p>Where a variation affects the Service Fees, project scope or project timeframe, Seventh Sky will provide a revised Quotation, Work Order or variation for approval before proceeding. Immediate action reasonably required to protect the Property, comply with legal obligations or ensure safety may be undertaken without prior approval where obtaining approval is not reasonably practicable.</p>`],
  ['THIRD-PARTY SERVICES', `<p>Where required, Seventh Sky may coordinate independent third-party professionals to support the delivery of the agreed Services, including surveyors, valuers, lawyers, accountants, contractors, agricultural specialists, insurers, utility providers, government authorities and other approved professional service providers.</p><p>The Client acknowledges that these providers operate independently and remain responsible for their own professional advice and services. Unless otherwise agreed in writing, Seventh Sky acts solely as the coordinator of these Services and is not responsible for the advice, reports, products or services provided by independent third parties.</p>`],
  ['SERVICE COMPLETION', `<p>The Services shall be deemed complete when Seventh Sky has substantially delivered the Services specified in the accepted Quotation, Work Order or Rural Property Management Schedule. Depending on the agreed scope, completion may include the property prepared for leasing, marketing activities completed, tenant sourcing and preliminary screening completed, lease documentation coordinated, rent collection arrangements established where included, routine inspections completed, maintenance coordination completed and management reports issued.</p><p>Where ongoing property management services are engaged, the Services shall continue until the expiry or termination of the agreed management period unless renewed by mutual agreement.</p>`],
  ['CLIENT COMPLAINTS', `<p>If the Client is dissatisfied with any aspect of the Services, the Client should notify Seventh Sky as soon as reasonably practicable. Upon receiving a complaint, Seventh Sky will acknowledge receipt, investigate the matter, communicate with the Client throughout the review process, take reasonable steps to resolve the issue where appropriate, and advise the Client of the outcome.</p><p>Where a complaint relates to a tenant, contractor or other independent third-party service provider, Seventh Sky will assist in facilitating communication where reasonably practicable but is not responsible for that third party's acts, omissions or performance. Nothing in this Agreement limits any rights available under applicable law.</p>`],
  ['LIABILITY', `<p>Seventh Sky will perform the agreed Services with reasonable care, skill and professional diligence. The Client acknowledges that Seventh Sky acts solely as a Rural Property Rental Management Service Provider and Coordinator and does not provide legal, financial, taxation, accounting, surveying, valuation, engineering, agricultural, insurance or investment advice.</p><p>The Client remains responsible for ownership and lawful leasing of the Property, compliance with all applicable laws and lease obligations, insurance arrangements, taxation obligations, maintenance and repair approvals, agricultural and commercial operations conducted on the Property, and obtaining independent professional advice where appropriate. Seventh Sky is not responsible for tenant decisions or conduct, tenant default or arrears, inaccurate information supplied by the Client, tenants or third parties, the acts or omissions of independent contractors or service providers, or professional advice provided by independent third-party professionals.</p>`],
  ['LIMITATION OF LIABILITY', `<p>To the maximum extent permitted by law, Seventh Sky shall not be liable for:</p>${ul(['failure to secure or retain tenants;', 'rental vacancies or changes in market conditions;', 'tenant default, rental arrears or breaches of tenancy agreements;', 'damage caused by tenants, contractors, livestock or third parties;', 'crop failure, flood, drought or other agricultural or environmental outcomes;', 'delays caused by contractors, utility providers or government authorities;', 'loss of rental income, loss of profit, loss of goodwill or other indirect or consequential loss; or', "events beyond Seventh Sky's reasonable control."])}<p>Where liability cannot legally be excluded, Seventh Sky's total liability shall not exceed the Professional Service Fees paid by the Client for the Services giving rise to the claim. Nothing in this clause excludes liability that cannot legally be excluded under applicable law.</p>`],
  ['CONFIDENTIALITY & PRIVACY', `<p>Both Parties agree to keep confidential all non-public information obtained through this Agreement. Seventh Sky may collect, use and disclose information only for the purpose of providing the agreed Services, marketing and managing the Property, communicating with the Client, prospective tenants and authorised third parties, coordinating contractors and approved service providers, preparing quotations, reports, invoices and management records, complying with legal obligations, and managing its business operations.</p><p>Neither Party shall disclose confidential information to any third party without prior consent unless required by law. These obligations continue after completion or termination of this Agreement.</p>`],
  ['FORCE MAJEURE', `<p>Neither Party shall be liable for delays or failure to perform its obligations where caused by events beyond its reasonable control, including natural disasters, floods, cyclones, drought, fire, pandemics, government restrictions, industrial action, utility failures, civil unrest or other unforeseen events. The affected Party shall notify the other Party as soon as reasonably practicable and resume performance once the event has ended.</p>`],
  ['OWNER ACKNOWLEDGEMENTS', `<p>The Client acknowledges that:</p>${ul(['they have read and understood this Agreement;', 'all information provided to Seventh Sky is true, accurate and complete to the best of their knowledge;', 'Seventh Sky provides Rural Property Rental Management Services only and does not own, lease or control the Property;', 'successful leasing depends on market conditions, tenant demand and property condition;', 'the final decision to approve or reject a tenant remains with the Client unless otherwise authorised in writing;', 'rental values and occupancy levels may change over time;', 'independent legal, taxation, financial, agricultural, engineering and other professional advice should be obtained where appropriate;', 'independent third-party professionals remain responsible for their own advice and services;', 'all agreed Professional Service Fees, approved expenses and third-party costs remain payable in accordance with this Agreement; and', 'they have had the opportunity to obtain independent legal advice before entering into this Agreement.'])}`],
  ['SUSPENSION & TERMINATION', `<p><b>21.1 Suspension.</b> Seventh Sky may suspend all or part of the Services where the Client fails to pay any outstanding amount in accordance with this Agreement, provides false, misleading or incomplete information, fails to provide information, approvals or instructions reasonably required to perform the Services, requests Seventh Sky to undertake any unlawful activity, or commits a material breach of this Agreement. Where reasonably practicable, Seventh Sky will notify the Client before suspending the Services.</p><p><b>21.2 Termination.</b> Either Party may terminate this Agreement by providing written notice to the other Party. Seventh Sky may terminate immediately where the Client commits a material breach, repeatedly fails to pay agreed Service Fees, engages in fraudulent or unlawful conduct, intentionally circumvents Seventh Sky in breach of this Agreement, or otherwise acts in a manner that makes continuation of the Services unreasonable. Upon termination, Professional Service Fees for Services already completed, approved third-party costs and management fees accrued before termination remain payable; obligations intended to survive termination continue; and termination does not affect rights or obligations accrued before the termination date.</p>`],
  ['NON-CIRCUMVENTION', `<p>The Client acknowledges that Seventh Sky invests considerable time, expertise and commercial resources in marketing properties, sourcing suitable tenants and coordinating leasing and property management services. Accordingly, where Seventh Sky introduces a prospective tenant, the Client agrees not to intentionally bypass Seventh Sky to avoid payment of the agreed Professional Service Fees or Management Fees.</p><p>This obligation applies during the term of this Agreement and for twelve (12) months following the introduction of the relevant tenant. This clause does not prevent the Client from leasing the Property to a tenant who was not introduced by Seventh Sky.</p>`],
  ['GENERAL PROVISIONS', `<p>Unless otherwise agreed in writing, this Agreement together with the accepted Quotation, Work Order, Rural Property Management Schedule and Schedules constitutes the entire agreement between the Parties; any amendment must be made in writing and accepted by both Parties; failure by either Party to enforce any provision shall not constitute a waiver of that provision; if any provision is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect; and notices under this Agreement may be delivered by hand, registered post, courier or email.</p>`],
  ['GOVERNING LAW', `<p>This Agreement shall be governed by the laws of the People's Republic of Bangladesh. The Parties agree to use reasonable efforts to resolve any dispute through good faith discussions before commencing legal proceedings. Where a dispute cannot be resolved through negotiation, either Party may refer the matter to the competent courts of Bangladesh.</p>`],
  ['EXECUTION', `<p>By signing this Agreement, the Parties confirm that they have read and understood this Agreement, have had the opportunity to obtain independent legal advice, agree to be bound by its terms, and enter into it voluntarily. This Agreement may be executed in counterparts and by electronic signature, each of which shall be deemed an original.</p>`],
];

const RURAL_PACK = {
  doc_no: 'SSPC-RPRMS-RURAL-01',
  title: 'Rural Property Rental Management Service Agreement',
  catalog_vertical: 'rural_pm',
  related_type: 'rural_property_management_agreement',
  cover_kicker: 'Rural Land & Rental Management',
  hero_eyebrow: 'Rural Leasing & Land Management',
  hero_title_html: 'Rural Property<br/>Rental Management<br/>Service Agreement',
  cover_intro: 'A governance framework establishing commercial terms, marketing &amp; tenant sourcing standards, rent administration, routine inspections and rural land care covenants between Seventh Sky Property Care and the Rural Property Owner / Landlord.',
  owner_label: 'Rural Property Owner / Landlord (Client)',
  schedule_b_title: 'SCHEDULE B — Rural Property Management Summary',
  schedule_d_title: 'SCHEDULE D — Rural Property Rental Management Checklist',
  clauses: RURAL_CLAUSES,
  service_groups: RURAL_SERVICE_GROUPS,
  checklist_groups: RURAL_CHECKLIST_GROUPS,
};

module.exports = { RURAL_PACK, RURAL_SERVICE_GROUPS, RURAL_CHECKLIST_GROUPS, RURAL_CLAUSES };
