/**
 * rptmRuralAgreementPack.js — the Rural Property Tenancy Management Service
 * Agreement content pack (SSPC-RPTMS-RURAL-01 v0.2).
 *
 * The TENANT side: Seventh Sky acts for the tenant, searching for and securing a
 * rural property — not for the landlord. Same 25-clause + Schedule A/B/C/D shape
 * as the residential and commercial tenancy packs, with the rural wording from
 * the source document. Consumed by rptmAgreement.service.js.
 *
 * NOTE: clause 22 states twelve (12) months of non-circumvention protection,
 * while the Rural Tenancy Management SOP §11 states 24. The agreement is what
 * the client signs, so the clause below says 12.
 */

// ── Schedule A: selectable rural tenancy service groups ───────────────────
const RURAL_TENANCY_SERVICE_GROUPS = {
  'Property Search': ['Initial Consultation', 'Tenant Requirement Assessment', 'Rural Property Search', 'Property Matching', 'Property Shortlisting', 'Off-Market Property Search'],
  'Property Assessment': ['Property Inspection Coordination', 'Site Visit Coordination', 'Property Suitability Assessment', 'Infrastructure & Access Review'],
  'Tenancy Coordination': ['Landlord Communication', 'Rental Negotiation Support', 'Lease Coordination', 'Occupancy Coordination', 'Property Handover Coordination', 'Utility Connection Coordination'],
  'Rural Property Support': ['Agricultural Property', 'Farm Property', 'Fishery Property', 'Orchard Property', 'Poultry / Dairy Property', 'Commercial Rural Property', 'Mixed-Use Rural Property'],
  'Additional Services': ['Legal Documentation Coordination', 'Property Valuation Coordination', 'Survey Coordination', 'Environmental Coordination', 'Other'],
};

// ── Schedule D: rural property tenancy management checklist groups ─────────
const RURAL_TENANCY_CHECKLIST_GROUPS = {
  'Client Engagement': ['Agreement Signed', 'Tenant Requirements Confirmed', 'Quotation / Work Order Approved', 'Deposit Received (If Applicable)'],
  'Property Search': ['Property Search Commenced', 'Suitable Properties Identified', 'Property Inspections Coordinated', 'Property Selected'],
  'Lease Coordination': ['Negotiations Completed', 'Lease Coordinated', 'Occupancy Arranged', 'Utility Coordination Completed'],
  Completion: ['Services Completed', 'Final Invoice Paid', 'Client Feedback Received', 'File Closed'],
};

const ul = (items) => `<ul style="margin:4px 0 8px 18px;padding:0;list-style-type:disc;">${items.map((i) => `<li style="margin:2px 0;">${i}</li>`).join('')}</ul>`;

// ── The 25 clauses, faithful to Rural Property Tenancy Management V0.2 ─────
const RURAL_TENANCY_CLAUSES = [
  ['PURPOSE', `<p>This Agreement sets out the terms and conditions under which Seventh Sky will provide Rural Property Tenancy Management Services to assist the Tenant in locating, assessing, negotiating and securing a suitable rural property for lease.</p><p>The Agreement establishes the rights and responsibilities of both Parties in relation to rural property search, tenancy coordination, landlord communication, lease coordination and other agreed tenancy support services.</p><p>The specific Services, pricing and engagement scope applicable to each tenancy shall be confirmed in the approved Quotation, Work Order or Rural Property Tenancy Schedule.</p>`],
  ['TERM', `<p>This Agreement commences on the date it is signed by both Parties and continues until:</p>${ul(['the agreed Services have been completed;', 'a tenancy has been secured;', 'this Agreement is terminated in accordance with its terms; or', 'both Parties otherwise agree in writing.'])}<p>Where ongoing tenancy management or support services are agreed, this Agreement continues for the period specified in the approved Work Order or Tenancy Schedule.</p>`],
  ['SERVICES', `<p>Depending on the selected Service Package, Seventh Sky may provide one or more of the Services listed in <b>Schedule A</b> (Property Search; Property Assessment; Tenancy Coordination; Rural Property Support; and Additional Services). Only the Services selected in Schedule A or the approved Work Order form part of this Agreement. Additional Services may be included by written agreement.</p>`],
  ['TENANCY REQUIREMENTS', `<p>The Tenant's tenancy requirements shall be recorded in <b>Schedule B</b> or the approved Rural Property Tenancy Schedule, and may include:</p>${ul(['Preferred District; Preferred Upazila; Preferred Union; Preferred Village;', 'Preferred Property Type; Intended Use;', 'Rental Budget; Preferred Lease Term;', 'Property Size Requirements; Infrastructure Requirements; Utility Requirements;', 'Selected Service Package; and Special Instructions.'])}<p>Where any inconsistency exists between this Agreement and the approved Work Order or Tenancy Schedule, the approved Work Order or Tenancy Schedule shall prevail for that engagement.</p>`],
  ['TENANT RESPONSIBILITIES', `<p>The Tenant agrees to:</p>${ul(['provide accurate and complete tenancy requirements;', 'provide a realistic rental budget and preferred lease conditions;', 'cooperate throughout the property search and tenancy process;', 'attend inspections where reasonably required;', 'promptly notify Seventh Sky of any changes to their requirements;', 'obtain independent legal, financial, taxation or technical advice where appropriate;', 'pay all agreed Service Fees and approved third-party costs in accordance with this Agreement; and', 'comply with all applicable laws relating to the intended use of the property.'])}<p>The Tenant remains responsible for selecting the property, entering into the lease agreement, complying with lease obligations, obtaining any licences, permits or approvals required for the intended use of the property, and making all final business, agricultural and financial decisions relating to the tenancy.</p>`],
  ['RESPONSIBILITIES OF SEVENTH SKY', `<p>Seventh Sky will:</p>${ul(['provide the agreed Services with reasonable care, skill and professional diligence;', "search for suitable rural properties based on the Tenant's requirements;", 'coordinate communications with landlords and their authorised representatives;', 'arrange property inspections;', 'assist with rental negotiations where authorised;', 'coordinate lease documentation and occupancy arrangements where included within the agreed Services;', 'maintain appropriate records relating to the engagement; and', 'keep the Tenant reasonably informed throughout the tenancy process.'])}<p>Unless otherwise agreed in writing, Seventh Sky acts as a Rural Property Tenancy Management Service Provider and Coordinator and does not act as the property owner, landlord, legal adviser, surveyor, valuer, engineer, accountant or government authority.</p>`],
  ['QUOTATIONS & WORK ORDERS', `<p>Before commencing the Services, Seventh Sky may issue a Quotation or Work Order specifying the agreed Services, Service Package, Service Fees, approved third-party costs, payment schedule, expected timeframe and any special conditions. Additional Services requested after commencement may require a revised Quotation, Work Order or approved variation before work proceeds.</p>`],
  ['SERVICE FEES & PAYMENT', `<p>The Service Fees payable under this Agreement shall be specified in the approved Quotation, Work Order or Rural Property Tenancy Schedule. Depending on the selected Service Package, the Service Fees may include Initial Consultation, Tenant Requirement Assessment, Rural Property Search, Property Inspection Coordination, Rental Negotiation Support, Lease Coordination, Occupancy &amp; Handover Coordination, Utility Connection Coordination, Approved Third-Party Costs and Additional Services requested by the Tenant.</p><p>The Tenant agrees to pay all agreed Service Fees in accordance with the approved payment schedule. Security deposits, advance rent, monthly rent, utility charges, government fees, legal fees, permit fees and other tenancy-related expenses remain the responsibility of the Tenant unless otherwise agreed in writing.</p>`],
  ['PAYMENT TERMS', `<p>Unless otherwise agreed in writing:</p>${ul(['<b>Professional Service Fees</b> are payable in accordance with the approved Quotation, Work Order or Rural Property Tenancy Schedule;', '<b>Leasing / Success Fee</b> — where agreed, it becomes payable upon successful completion of the agreed milestone specified in the approved engagement documents; and', '<b>Third-Party Costs</b> — approved third-party expenses, including legal, valuation, survey, engineering, environmental, travel or inspection costs, shall be payable by the Tenant.'])}<p>Invoices are payable within the period stated on the invoice. Late payments may result in suspension of the Services until outstanding amounts have been paid.</p>`],
  ['RURAL PROPERTY TENANCY SERVICES', `<p>Seventh Sky will use reasonable efforts to assist the Tenant in locating and securing a suitable rural property in accordance with the agreed scope of Services, which depending on the selected Service Package may include property search and shortlisting, landlord communication, property inspection coordination, property suitability support, rental negotiation, lease coordination, occupancy and handover coordination, utility connection coordination and other agreed tenancy support services.</p><p>The Tenant acknowledges that property availability depends on market conditions; landlords are under no obligation to accept any tenancy application; Seventh Sky does not guarantee that a suitable property will be found within a particular timeframe or budget; and the final decision to enter into any lease remains solely with the Tenant.</p>`],
  ['PROJECT TIMELINES', `<p>Estimated commencement and completion dates will be provided in the approved Quotation or Work Order where applicable. Timeframes may vary depending on property availability, landlord responsiveness, inspection scheduling, seasonal and weather conditions, negotiation progress, government approvals, public holidays and other circumstances beyond Seventh Sky's reasonable control. Where delays occur, Seventh Sky will keep the Tenant reasonably informed and provide revised estimated timeframes where reasonably practicable.</p>`],
  ['VARIATIONS & ADDITIONAL SERVICES', `<p>The Tenant may request changes to the agreed scope of Services at any time. Additional Services may include additional property searches, additional inspections, extended negotiation support, legal documentation coordination, survey or environmental coordination, or any other Services requested by the Tenant.</p><p>Where a variation affects the Service Fees, scope or timeframe, Seventh Sky will provide a revised Quotation, Work Order or variation for approval before proceeding.</p>`],
  ['THIRD-PARTY SERVICES', `<p>Where required, Seventh Sky may coordinate independent third-party professionals to support the delivery of the agreed Services, including lawyers, surveyors, valuers, accountants, agricultural specialists, environmental consultants, utility providers, government authorities and other approved professional service providers.</p><p>The Tenant acknowledges that these providers operate independently and remain responsible for their own professional advice and services. Unless otherwise agreed in writing, Seventh Sky acts solely as the coordinator of these Services and is not responsible for the advice, reports, products or services provided by independent third parties.</p>`],
  ['SERVICE COMPLETION', `<p>The Services shall be deemed complete when Seventh Sky has substantially delivered the Services specified in the accepted Quotation, Work Order or Rural Property Tenancy Schedule. Depending on the agreed scope, completion may include the property search completed, inspections coordinated, negotiations supported, lease documentation coordinated, occupancy arranged and utility coordination completed.</p>`],
  ['CLIENT COMPLAINTS', `<p>If the Tenant is dissatisfied with any aspect of the Services, the Tenant should notify Seventh Sky as soon as reasonably practicable. Upon receiving a complaint, Seventh Sky will acknowledge receipt, investigate the matter, communicate with the Tenant throughout the review process, take reasonable steps to resolve the issue where appropriate, and advise the Tenant of the outcome.</p><p>Where a complaint relates to a landlord, contractor or other independent third-party service provider, Seventh Sky will assist in facilitating communication where reasonably practicable but is not responsible for that third party's acts, omissions or performance. Nothing in this Agreement limits any rights available under applicable law.</p>`],
  ['LIABILITY', `<p>Seventh Sky will perform the agreed Services with reasonable care, skill and professional diligence. The Tenant acknowledges that Seventh Sky acts solely as a Rural Property Tenancy Management Service Provider and Coordinator and does not provide legal, financial, taxation, accounting, surveying, valuation, engineering, agricultural, insurance or investment advice.</p><p>The Tenant remains responsible for selecting the property, entering into and complying with the lease, obtaining licences and permits for the intended use, the suitability of the property for the intended agricultural or commercial activity, and obtaining independent professional advice where appropriate. Seventh Sky is not responsible for landlord decisions or conduct, inaccurate information supplied by landlords or third parties, the acts or omissions of independent contractors or service providers, or professional advice provided by independent third-party professionals.</p>`],
  ['LIMITATION OF LIABILITY', `<p>To the maximum extent permitted by law, Seventh Sky shall not be liable for:</p>${ul(['failure to locate a suitable property within a particular timeframe or budget;', 'a landlord declining a tenancy application or withdrawing a property;', 'changes in market conditions, rental values or property availability;', 'the condition, suitability or productivity of any property;', 'crop failure, flood, drought or other agricultural or environmental outcomes;', 'delays caused by landlords, contractors, utility providers or government authorities;', 'loss of profit, loss of opportunity, loss of goodwill or other indirect or consequential loss; or', "events beyond Seventh Sky's reasonable control."])}<p>Where liability cannot legally be excluded, Seventh Sky's total liability shall not exceed the Professional Service Fees paid by the Tenant for the Services giving rise to the claim.</p>`],
  ['CONFIDENTIALITY & PRIVACY', `<p>Both Parties agree to keep confidential all non-public information obtained through this Agreement. Seventh Sky may collect, use and disclose information only for the purpose of providing the agreed Services, communicating with the Tenant, landlords and authorised third parties, coordinating inspections and approved service providers, preparing quotations, reports, invoices and engagement records, complying with legal obligations, and managing its business operations.</p><p>Neither Party shall disclose confidential information to any third party without prior consent unless required by law. These obligations continue after completion or termination of this Agreement.</p>`],
  ['FORCE MAJEURE', `<p>Neither Party shall be liable for delays or failure to perform its obligations where caused by events beyond its reasonable control, including natural disasters, floods, cyclones, drought, fire, pandemics, government restrictions, industrial action, utility failures, civil unrest or other unforeseen events. The affected Party shall notify the other Party as soon as reasonably practicable and resume performance once the event has ended.</p>`],
  ['TENANT ACKNOWLEDGEMENTS', `<p>The Tenant acknowledges that:</p>${ul(['they have read and understood this Agreement;', 'all information provided to Seventh Sky is true, accurate and complete to the best of their knowledge;', 'Seventh Sky provides Rural Property Tenancy Management Services only and does not own, lease or control any property;', 'property availability depends on market conditions and landlord decisions;', 'the final decision to enter into any lease remains solely with the Tenant;', 'independent legal, taxation, financial, agricultural and other professional advice should be obtained where appropriate;', 'independent third-party professionals remain responsible for their own advice and services;', 'all agreed Professional Service Fees, approved expenses and third-party costs remain payable in accordance with this Agreement; and', 'they have had the opportunity to obtain independent legal advice before entering into this Agreement.'])}`],
  ['SUSPENSION & TERMINATION', `<p><b>21.1 Suspension.</b> Seventh Sky may suspend all or part of the Services where the Tenant fails to pay any outstanding amount, provides false, misleading or incomplete information, fails to provide information, approvals or instructions reasonably required, requests Seventh Sky to undertake any unlawful activity, or commits a material breach of this Agreement. Where reasonably practicable, Seventh Sky will notify the Tenant before suspending the Services.</p><p><b>21.2 Termination.</b> Either Party may terminate this Agreement by providing written notice to the other Party. Seventh Sky may terminate immediately where the Tenant commits a material breach, repeatedly fails to pay agreed Service Fees, engages in fraudulent or unlawful conduct, intentionally circumvents Seventh Sky in breach of this Agreement, or otherwise acts in a manner that makes continuation of the Services unreasonable. Upon termination, Professional Service Fees for Services already completed and approved third-party costs remain payable; obligations intended to survive termination continue; and termination does not affect rights or obligations accrued before the termination date.</p>`],
  ['NON-CIRCUMVENTION', `<p>The Tenant acknowledges that Seventh Sky invests considerable time, resources and expertise in identifying suitable rural properties, communicating with landlords, coordinating inspections and assisting with tenancy negotiations. Accordingly, where Seventh Sky introduces a property, landlord or authorised representative, the Tenant agrees not to intentionally bypass Seventh Sky to avoid payment of the agreed Professional Service Fees.</p><p>This obligation applies during the term of this Agreement and for twelve (12) months following the introduction of the relevant property or landlord. This clause does not prevent the Tenant from leasing a property that was not introduced by Seventh Sky.</p>`],
  ['GENERAL PROVISIONS', `<p>Unless otherwise agreed in writing, this Agreement together with the accepted Quotation, Work Order, Rural Property Tenancy Schedule and Schedules constitutes the entire agreement between the Parties; any amendment must be made in writing and accepted by both Parties; failure by either Party to enforce any provision shall not constitute a waiver of that provision; if any provision is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect; and notices under this Agreement may be delivered by hand, registered post, courier or email.</p>`],
  ['GOVERNING LAW', `<p>This Agreement shall be governed by the laws of the People's Republic of Bangladesh. The Parties agree to use reasonable efforts to resolve any dispute through good faith discussions before commencing legal proceedings. Where a dispute cannot be resolved through negotiation, either Party may refer the matter to the competent courts of Bangladesh.</p>`],
  ['EXECUTION', `<p>By signing this Agreement, the Parties confirm that they have read and understood this Agreement, have had the opportunity to obtain independent legal advice, agree to be bound by its terms, and enter into it voluntarily. This Agreement may be executed in counterparts and by electronic signature, each of which shall be deemed an original.</p>`],
];

const RURAL_TENANCY_PACK = {
  doc_no: 'SSPC-RPTMS-RURAL-01',
  title: 'Rural Property Tenancy Management Service Agreement',
  catalog_vertical: 'rural_tenancy_mgmt',
  related_type: 'rural_tenancy_management_agreement',
  cover_kicker: 'Rural Tenancy & Property Search',
  hero_eyebrow: 'Tenant Representation & Rural Sourcing',
  hero_title_html: 'Rural Property<br/>Tenancy Management<br/>Service Agreement',
  cover_intro: 'An engagement framework establishing the terms on which Seventh Sky Property Care searches for, assesses, negotiates and secures a suitable rural property on behalf of the Tenant, including landlord communication, inspection coordination, lease coordination and occupancy support.',
  owner_label: 'Tenant (Client)',
  provider_label: 'Rural Tenancy Manager (Acting for the Tenant)',
  acting_line: 'Acting on behalf of: <strong>The Tenant</strong>',
  footer_line: 'Seventh Sky Property Care · Rural Tenancy Agreement SSPC-RPTMS-RURAL-01 v0.2',
  schedule_b_title: 'SCHEDULE B — Rural Tenancy Requirement Summary',
  schedule_d_title: 'SCHEDULE D — Rural Property Tenancy Management Checklist',
  clauses: RURAL_TENANCY_CLAUSES,
  service_groups: RURAL_TENANCY_SERVICE_GROUPS,
  checklist_groups: RURAL_TENANCY_CHECKLIST_GROUPS,
};

module.exports = {
  RURAL_TENANCY_PACK,
  RURAL_TENANCY_CLAUSES,
  RURAL_TENANCY_SERVICE_GROUPS,
  RURAL_TENANCY_CHECKLIST_GROUPS,
};
