/**
 * Route manifest — the single source of truth for every API route mount.
 *
 * Both the standalone API (backend/server.js) and the Hostinger monolith
 * (production-server.js) mount from this list so they can never drift apart.
 * Each entry is [mountPath, moduleRelativeToThisFile].
 */
module.exports = [
  ['/api/auth', './auth.routes'],
  ['/api/rbac', './rbac.routes'],
  ['/api/settings', './settings.routes'],
  ['/api/notifications', './notification.routes'],
  ['/api/branches', './branch.routes'],
  ['/api/automation', './automation.routes'],
  ['/api/dashboard', './dashboard.routes'],
  ['/api/payment', './payment.routes'],
  ['/api/hrm', './hrm.routes'],
  ['/api/payroll', './payroll.routes'],
  ['/api/assets', './asset.routes'],
  ['/api/expenses', './expense.routes'],
  ['/api/invoices', './invoicing.routes'],
  ['/api/billing', './billing.routes'],
  ['/api/account-categories', './accountCategory.routes'],
  ['/api/folios', './folio.routes'],
  ['/api/payments', './paymentsList.routes'],
  ['/api/budget', './budget.routes'],
  ['/api/accounting', './accounting.routes'],
  ['/api/finance', './finance.routes'],
  ['/api/reconciliation', './reconciliation.routes'],
  ['/api/contacts', './contact.routes'],
  ['/api/party-role-profiles', './partyRoleProfile.routes'],
  ['/api/clients', './client.routes'],
  ['/api/properties', './property.routes'],
  ['/api/tenancies', './tenancy.routes'],
  ['/api/tenant-applications', './tenantApplication.routes'],
  ['/api/rental-assessments', './rentalAssessment.routes'],
  ['/api/rental-enquiries', './rentalEnquiry.routes'],
  ['/api/property-management', './propertyManagement.routes'],
  ['/api/owner-statements', './ownerStatement.routes'],
  ['/api/landlord', './landlord.routes'],
  ['/api/tenant', './tenant.routes'],
  ['/api/vacancy-notices', './vacancyNotice.routes'],
  ['/api/deposit-settlements', './depositSettlement.routes'],
  ['/api/rental-reports', './rentalReports.routes'],
  ['/api/disbursements', './disbursement.routes'],
  ['/api/uploads', './upload.routes'],
  ['/api/service-catalog', './serviceCatalog.routes'],
  ['/api/public-provider', './publicProvider.routes'],
  ['/api/care', './care.routes'],
  ['/api/agreement-templates', './agreementTemplate.routes'],
  ['/api/kyc', './kyc.routes'],
  ['/api/utility-bills', './utilityBill.routes'],
  ['/api/tenant-requests', './tenantRequest.routes'],
  ['/api/arrears-actions', './arrearsAction.routes'],
  ['/api/marketing-activities', './marketingActivity.routes'],
  ['/api/expense-approvals', './expenseApproval.routes'],
  ['/api/property-risks', './propertyRisk.routes'],
  ['/api/move-in-checklist', './moveInChecklist.routes'],
  ['/api/public-party', './publicParty.routes'],
  ['/api/deals', './deal.routes'],
  ['/api/sales', './sales.routes'],
  ['/api/sales-payments', './salesPayment.routes'],
  ['/api/services', './service.routes'],
  ['/api/leads', './lead.routes'],
  ['/api/providers', './provider.routes'],
  ['/api/projects', './project.routes'],
  ['/api/registers', './register.routes'],
  ['/api/work-orders', './workOrder.routes'],
  ['/api/inspections', './inspection.routes'],
  ['/api/documents', './document.routes'],
  ['/api/signing', './signing.routes'],
  ['/api/agreements', './agreement.routes'],
  ['/api/sign', './sign.routes'],
  ['/api/intake', './intake.routes'],
  ['/api/portal', './portal.routes'],
  ['/api/public', './public.routes'],
];
