const { DataTypes } = require('sequelize');
const sequelize = require('../config/db.config');

const ServiceProvider = sequelize.define('ServiceProvider', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  branch_id: { type: DataTypes.INTEGER, allowNull: false },
  provider_code: { type: DataTypes.STRING(40), unique: true },
  contact_id: DataTypes.INTEGER,
  company_name: { type: DataTypes.STRING, allowNull: false },
  contact_person: DataTypes.STRING,
  phone: DataTypes.STRING,
  email: DataTypes.STRING,
  address: DataTypes.TEXT,
  specialisations: { type: DataTypes.JSON, defaultValue: [] },
  service_categories: { type: DataTypes.JSON, defaultValue: [] },
  coverage_areas: { type: DataTypes.JSON, defaultValue: [] },
  availability: { type: DataTypes.ENUM('available', 'busy', 'unavailable'), defaultValue: 'available' },
  portal_enabled: { type: DataTypes.BOOLEAN, defaultValue: false },
  portal_user_id: DataTypes.INTEGER,
  rate_card: { type: DataTypes.JSON, defaultValue: {} },
  bank_details: { type: DataTypes.JSON, defaultValue: {} },
  rating: DataTypes.DECIMAL(3, 2),
  internal_notes: DataTypes.TEXT,
  non_circumvention_agreed: { type: DataTypes.BOOLEAN, defaultValue: false },
  status: { type: DataTypes.ENUM('pending_onboarding', 'approved', 'suspended', 'terminated', 'inactive'), defaultValue: 'pending_onboarding' },
  onboarded_at: DataTypes.DATE,
  // Phase 2 — full onboarding profile
  provider_type: { type: DataTypes.ENUM('third_party', 'internal'), defaultValue: 'third_party' },
  vertical: DataTypes.STRING(60),
  trade_licence_no: DataTypes.STRING,
  company_reg_no: DataTypes.STRING,
  tin: DataTypes.STRING,
  bin: DataTypes.STRING,
  account_manager_id: DataTypes.INTEGER,
  onboarding_stage: { type: DataTypes.ENUM('applied', 'kyc_submitted', 'verifying', 'agreement_pending', 'active', 'suspended', 'terminated'), defaultValue: 'applied' },
  kyc_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  compliance_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  insurance_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  capability_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  payment_verified: { type: DataTypes.BOOLEAN, defaultValue: false },
  agreement_status: { type: DataTypes.ENUM('none', 'sent', 'signed'), defaultValue: 'none' },
  verified_at: DataTypes.DATE,
  districts: { type: DataTypes.JSON, defaultValue: null },
  cities: { type: DataTypes.JSON, defaultValue: null },
  cumilla_restricted: { type: DataTypes.BOOLEAN, defaultValue: false },
  exclusive_territory: { type: DataTypes.BOOLEAN, defaultValue: false },
  preferred_payment: DataTypes.STRING(40),
  folio_id: DataTypes.INTEGER,
  registration_token: DataTypes.STRING(80),
  registration_expires_at: DataTypes.DATE,
  registration_submitted_at: DataTypes.DATE,
  created_by: DataTypes.INTEGER,
}, { tableName: 'service_providers', underscored: true });

module.exports = ServiceProvider;
